config/routes.rb
Rails.application.routes.draw do
  resources :instructors
  resources :students
  resources :courses
 

  get "/user/:id", to: "users#show", as: :user
  devise_for :users, controllers: { registrations: 'users/registrations',
                                      sessions: 'users/sessions' }

  root to: 'home#index'
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  belongs_to :user
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        User.update(current_user.id, instructor_id: @instructor.id)
        format.html { redirect_to user_path(current_user.id), notice: 'instructor was successfully created.' }
        # format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :email, :school, :dept, :rank, :phone, :address, :user_id)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.hidden_field :first_name, value: current_user.first_name %>
  </div>
  <div class="field">
    <%= f.hidden_field :last_name, value: current_user.last_name %>
  </div>
  <div class="field">
    <%= f.hidden_field :email, value: current_user.email %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :dept %><br>
    <%= f.text_field :dept %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing instructors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Dept</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.first_name %></td>
        <td><%= instructor.last_name %></td>
        <td><%= instructor.email %></td>
        <td><%= instructor.phone %></td>
        <td><%= instructor.address %></td>
        <td><%= instructor.dept %></td>
        <td><%= instructor.rank %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @instructor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @instructor.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @instructor.address %>
</p>

<p>
  <strong>Dept:</strong>
  <%= @instructor.dept %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @instructor.rank %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>